#!/bin/zsh

typeset -gA key=(
    Tab           $'\t'
    Shift-Tab     $'\e[Z'
    Return        $'\r'
    Backspace     $'\C-?'
    Delete        $'\e[3~'
    Control-Space $'\0'
    Up            $'\e[A'
    Alt-Up        $'\e[1;3A'
    Down          $'\e[B'
    Alt-Down      $'\e[1;3B'
    Left          $'\e[D'
    Right         $'\e[C'
    PageUp        $'\e[5~'
    PageDown      $'\e[6~'
    Home          $'\e[H'
    End           $'\e[F'
)
