#!/bin/zsh
# This is picked up automatically by /etc/zshrc
typeset -gA key=(
    Tab           $'\t'
    Shift-Tab     $'\e[Z'
    Return        $'\r'
    Backspace     $'\C-?'
    Delete        $'\e[3~'
    Control-Space $'\0'
    Up            $'\e[A'
    Alt-Up        $'\e\e[A'
    Down          $'\e[B'
    Alt-Down      $'\e\e[B'
    Left          $'\e[D'
    Right         $'\e[C'
    PageUp        $'\e[5~'
    PageDown      $'\e[6~'
    Home          $'\e[H'
    End           $'\e[F'
)
